# Learning Rate
lr_encoder: 1e-6
lr_others: 1.5e-5
weight_decay_encoder: 0.001
weight_decay_other: 0.001

# Training Parameters
num_steps: 41
warmup_ratio: 0.1
train_batch_size: 1
eval_every: 41
gradient_accumulation: 8 #null
eval_batch_size: 1
num_layers_freeze: 18
early_stopping_patience: 5
early_stopping_delta: 0.005

# Model Configuration
max_width: 12
model_name: microsoft/deberta-v3-large
fine_tune: true
subtoken_pooling: first
hidden_size: 768
scorer: "dot" # "dot_norm" # "dot"
rel_mode: marker
span_marker_mode: markerv1
refine_prompt: false
refine_relation: false
ffn_mul: 4
dropout: 0.25
scheduler: "cosine_with_warmup"  # "cosine_with_hard_restarts" #cosine_with_warmup
loss_func: "binary_cross_entropy_loss" # "binary_cross_entropy_loss"  # "focal_loss"
alpha: 0.6
gamma: 3
# add_entity_markers: true
label_embed_strategy: "both"  # "label" "ent_token" "both"

# Coreference Resolution
coref_classifier: false
coref_loss_weight: 10.0

# Training Specifics
size_sup: -1
num_train_rel_types: 12   # number of relation labels to use in each given mini-batch
num_unseen_rel_types: 7   
top_k: 1                  # number of relations predictions to return at evaluation time
random_drop: false       # randomly drop relation types
max_len: 512
eval_threshold: [0.01, 0.1, 0.2, 0.3, 0.5]
max_entity_pair_distance: 128
fixed_relation_types: true  # for eval: only use the given list of relation types (FewRel) for all batches
gradient_checkpointing: true
fp16: true
max_grad_norm: 1.0

prev_path: "jackboyla/glirel-large-v0"

name: "drugprot"
